copy ..\01_A\dune_folder.txt ..\02_B /Y
copy ..\01_A\dune_folder.txt ..\03_C /Y
copy ..\01_A\dune_folder.txt ..\04_D /Y
copy ..\01_A\dune_folder.txt ..\05_E /Y
copy ..\01_A\dune_folder.txt ..\06_F /Y
copy ..\01_A\dune_folder.txt ..\07_G /Y
copy ..\01_A\dune_folder.txt ..\08_H /Y
copy ..\01_A\dune_folder.txt ..\09_I /Y
copy ..\01_A\dune_folder.txt ..\10_J /Y
copy ..\01_A\dune_folder.txt ..\11_K /Y
copy ..\01_A\dune_folder.txt ..\12_L /Y
copy ..\01_A\dune_folder.txt ..\13_M /Y
copy ..\01_A\dune_folder.txt ..\14_N /Y
copy ..\01_A\dune_folder.txt ..\15_O /Y
copy ..\01_A\dune_folder.txt ..\16_P /Y
copy ..\01_A\dune_folder.txt ..\17_Q /Y
copy ..\01_A\dune_folder.txt ..\18_R /Y
copy ..\01_A\dune_folder.txt ..\19_S /Y
copy ..\01_A\dune_folder.txt ..\20_T /Y
copy ..\01_A\dune_folder.txt ..\21_U /Y
copy ..\01_A\dune_folder.txt ..\22_V /Y
copy ..\01_A\dune_folder.txt ..\23_W /Y
copy ..\01_A\dune_folder.txt ..\24_X /Y
copy ..\01_A\dune_folder.txt ..\25_Y /Y
copy ..\01_A\dune_folder.txt ..\26_Z /Y
copy ..\01_A\dune_folder.txt ..\27_# /Y
copy ..\01_A\dune_folder.txt ..\28_- /Y
